### Display MTEB results
MTEB results are saved in .json files, one for each task. 
This notebook aggregates the results for multiple tasks and multiple models.

In [38]:
import os
os.getcwd()

'/gpfs01/berens/user/lholzwarth'

In [39]:
import mteb
import json
import pandas as pd

In [40]:
# get task type 
mteb.get_task("ArguAna").metadata.type

'Retrieval'

In [41]:
data = {}
main_dir = "/gpfs01/berens/user/lholzwarth/text_embedding/MTEB/sparse_results"

# Traverse folders and subfolders
for (root, dirs, files) in os.walk(main_dir):
    # Identify model version from the folder structure
    model_version = os.path.basename(root)
    print(model_version)
        
    for file in files:
        # Skip unwanted files
        if file in {"model_meta.json"} or not file.endswith('.json'):
            continue
            
        file_path = os.path.join(root, file)
        try:
            # Read JSON and extract necessary fields
            with open(file_path, 'r') as f:
                json_data = json.load(f)
                task_name = json_data.get("task_name")
                main_score = json_data.get("scores", {}).get("test", {})[0]["main_score"]
                main_score = round(main_score*100, 2)
                    
                if task_name and main_score is not None:
                    if task_name not in data:
                        data[task_name] = {}
                    data[task_name][model_version] = main_score
        except (json.JSONDecodeError, KeyError):
            print(f"Error parsing file: {file_path}")

sparse_results
Tfidf
tfidf_log
tfidf_rnd100_log
tfidf_log_run1
1.0
Error parsing file: /gpfs01/berens/user/lholzwarth/text_embedding/MTEB/sparse_results/Tfidf/1.0/BibleNLPBitextMining.json
svd_log_old
svd
svd_log_run2
svd_log_old_run1
svd_log_run1
tfidf_rnd768_log
sentence-transformers__average_word_embeddings_glove.6B.300d
no_revision_available

In [42]:
df = pd.DataFrame.from_dict(data, orient='index')
df.index.name = "task_name"
df["task_types"] = [mteb.get_task(task).metadata.type for task in df.index]
df

,tfidf_log,tfidf_rnd100_log,tfidf_log_run1,1.0,svd_log_run2,svd_log_old_run1,svd_log_run1,tfidf_rnd768_log,svd_log_old,svd,no_revision_available,task_types
task_name,,,,,,,,,,,,
ArxivClusteringP2P,34.79,8.32,35.28,26.72,40.23,41.73,40.23,29.12,NaN,NaN,NaN,Clustering
BiorxivClusteringP2P,26.21,4.00,26.44,20.56,33.74,33.80,33.74,18.14,NaN,NaN,NaN,Clustering
SciDocsRR,62.32,52.08,62.32,62.30,52.71,NaN,52.71,61.72,NaN,NaN,NaN,Reranking
SCIDOCS,14.73,3.83,14.69,13.31,5.31,NaN,5.31,12.57,NaN,NaN,NaN,Retrieval
MedrxivClusteringP2P,22.02,11.16,20.82,19.30,30.11,30.00,30.11,17.13,NaN,NaN,NaN,Clustering
MindSmallReranking,22.49,24.75,23.45,23.44,26.63,NaN,26.63,27.00,NaN,NaN,NaN,Reranking
ArguAna,52.52,11.63,52.54,42.48,41.35,NaN,41.35,43.38,NaN,NaN,NaN,Retrieval
RedditClusteringP2P,39.94,11.37,40.34,31.54,34.59,45.96,34.59,32.42,46.5,NaN,NaN,Clustering
StackExchangeClusteringP2P,NaN,17.87,17.53,18.80,34.12,34.01,34.12,17.00,NaN,NaN,NaN,Clustering
STSBenchmark,NaN,66.46,68.57,69.23,44.72,NaN,44.72,68.44,NaN,NaN,NaN,STS
STS15,NaN,70.74,73.43,74.01,52.51,NaN,52.51,73.06,NaN,NaN,NaN,STS
STS16,NaN,67.48,70.25,70.25,46.80,NaN,46.80,69.73,NaN,NaN,NaN,STS
EmotionClassification,NaN,NaN,NaN,25.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Classification
TwitterSemEval2015,NaN,NaN,NaN,57.66,NaN,NaN,55.12,NaN,NaN,NaN,NaN,PairClassification
BIOSSES,NaN,NaN,NaN,76.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STS
ArXivHierarchicalClusteringS2S,NaN,NaN,NaN,50.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clustering
MassiveIntentClassification,NaN,NaN,NaN,39.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Classification
MedrxivClusteringS2S,NaN,NaN,NaN,15.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clustering
BiorxivClusteringS2S,NaN,NaN,NaN,7.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clustering
ArxivClusteringS2S,NaN,NaN,NaN,11.54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clustering
DiaBlaBitextMining,NaN,NaN,NaN,5.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BitextMining
NFCorpus,NaN,NaN,NaN,27.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Retrieval
SummEval,NaN,NaN,NaN,25.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Summarization
ImdbClassification,NaN,NaN,NaN,58.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Classification
Banking77Classification,NaN,NaN,NaN,63.88,NaN,NaN,57.19,NaN,NaN,2.81,67.8,Classification
BUCC.v2,NaN,NaN,NaN,2.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BitextMining
AmazonCounterfactualClassification,NaN,NaN,NaN,79.75,NaN,41.69,NaN,NaN,NaN,NaN,NaN,Classification
AskUbuntuDupQuestions,NaN,NaN,NaN,51.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reranking
SummEvalSummarization.v2,NaN,NaN,NaN,18.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Summarization
AmazonPolarityClassification,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.0,Classification

In [43]:
task_selection = ["ArguAna", "ArxivClusteringP2P", "BiorxivClusteringP2P", "MedrxivClusteringP2P", "MindSmallReranking",
                 "RedditClusteringP2P", "SCIDOCS", "SciDocsRR", "StackExchangeClusteringP2P", "STS15", "STS16",
                 "STSBenchmark"]

df.loc[task_selection].sort_values("task_types")

,tfidf_log,tfidf_rnd100_log,tfidf_log_run1,1.0,svd_log_run2,svd_log_old_run1,svd_log_run1,tfidf_rnd768_log,svd_log_old,svd,no_revision_available,task_types
task_name,,,,,,,,,,,,
ArxivClusteringP2P,34.79,8.32,35.28,26.72,40.23,41.73,40.23,29.12,NaN,NaN,NaN,Clustering
BiorxivClusteringP2P,26.21,4.00,26.44,20.56,33.74,33.80,33.74,18.14,NaN,NaN,NaN,Clustering
MedrxivClusteringP2P,22.02,11.16,20.82,19.30,30.11,30.00,30.11,17.13,NaN,NaN,NaN,Clustering
RedditClusteringP2P,39.94,11.37,40.34,31.54,34.59,45.96,34.59,32.42,46.5,NaN,NaN,Clustering
StackExchangeClusteringP2P,NaN,17.87,17.53,18.80,34.12,34.01,34.12,17.00,NaN,NaN,NaN,Clustering
MindSmallReranking,22.49,24.75,23.45,23.44,26.63,NaN,26.63,27.00,NaN,NaN,NaN,Reranking
SciDocsRR,62.32,52.08,62.32,62.30,52.71,NaN,52.71,61.72,NaN,NaN,NaN,Reranking
ArguAna,52.52,11.63,52.54,42.48,41.35,NaN,41.35,43.38,NaN,NaN,NaN,Retrieval
SCIDOCS,14.73,3.83,14.69,13.31,5.31,NaN,5.31,12.57,NaN,NaN,NaN,Retrieval
STS15,NaN,70.74,73.43,74.01,52.51,NaN,52.51,73.06,NaN,NaN,NaN,STS
STS16,NaN,67.48,70.25,70.25,46.80,NaN,46.80,69.73,NaN,NaN,NaN,STS
STSBenchmark,NaN,66.46,68.57,69.23,44.72,NaN,44.72,68.44,NaN,NaN,NaN,STS